#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$PWD"

# if [ -d "$ROOT_DIR/MG5_aMC_v2_9_27" ]; then
#     echo "[skip] MG5_aMC_v2_9_27 already exists -> skipping download"
if [ -d "$ROOT_DIR/MG5_aMC_v3_7_2" ]; then
    echo "[skip] MG5_aMC_v3_7_2 already exists -> skipping download"
else
    wget https://launchpad.net/mg5amcnlo/3.0/3.7.x/+download/MG5_aMC_v3.7.2.tar.gz
    tar -axvf MG5_aMC_v3.7.2.tar.gz
    rm MG5_aMC_v3.7.2.tar.gz
#     wget https://launchpad.net/mg5amcnlo/lts/2.9.x/+download/MG5_aMC_v2.9.27.tar.gz
#     tar -axvf MG5_aMC_v2.9.27.tar.gz
#     rm MG5_aMC_v2.9.27.tar.gz
fi
# cd "$ROOT_DIR/MG5_aMC_v2_9_27/models"
cd "$ROOT_DIR/MG5_aMC_v3_7_2/models"

if [ -d "SMEFTsim_topU3l_MwScheme_UFO" ]; then
    echo "[skip] SMEFTsim_topU3l_MwScheme_UFO already exists -> skipping clone"
else
    rm -rf SMEFTsim
    git clone git@github.com:SMEFTsim/SMEFTsim.git
    mv SMEFTsim/UFO_models/SMEFTsim_topU3l_MwScheme_UFO .
    rm -rf SMEFTsim
fi
cd SMEFTsim_topU3l_MwScheme_UFO/

BASE="restrict_SMlimit_massless.dat"
COEFF="cHWB"
# The trick: this must be a generic, non-special value -- NOT exactly 0 or 1.
# MG5 hardcodes/prunes a parameter restricted to 0 or 1 (dropping its Block
# SMEFT entry from param_card.dat), but leaves any other value -- like this
# one -- external/settable. create.sh depends on that: it reuses this same
# restriction card for PROC_cHWB_NP1, whose reweight_card.dat needs cHWB to
# still be a settable parameter.
VALUE="9.999999e-01"
OUT="restrict_${COEFF}_massless.dat"

if [ -f "$OUT" ]; then
    echo "[skip] $OUT already exists"
else
    sed -E "s/^(.*)0\.000000e\+00( # ${COEFF}[[:space:]]*)\$/\1${VALUE}\2/" \
        "$BASE" > "$OUT"
fi


# ---------------------------------------------------------------------------
# Portability fix: MG5's f2py toolchain. Local only -- no downloads, no
# execution of remote code. Safe to rerun.
#
# MG5's "f2py_compiler_py3" config option can only ever hold a single
# executable token: do_set() in madgraph/interface/common_run_interface.py
# tokenizes the config line on whitespace and keeps only args[1], and
# misc.which() can't resolve a value containing spaces either way -- so a
# multi-word command like "python3 -m numpy.f2py" can never be set directly.
# On macOS specifically, Homebrew's f2py/f2py3/f2py3.10/f2py3.11 binaries are
# commonly stale symlinks into an old numpy Cellar path whose shebang points
# at a python3.x Homebrew has since removed -> compile fails with "f2py: No
# such file or directory".
#
# Fix: generate a single-token wrapper script around a python3 this script
# has actually verified has a working numpy.f2py, and point MG5's config at
# that wrapper instead of the real (multi-word) command.

# MG5_DIR="$ROOT_DIR/MG5_aMC_v2_9_27"
MG5_DIR="$ROOT_DIR/MG5_aMC_v3_7_2"


echo "==> Looking for a working python3 + numpy.f2py ..."
PYTHON3=""
for CAND in python3 /usr/bin/python3 /opt/homebrew/bin/python3 /usr/local/bin/python3 \
            python3.13 python3.12 python3.11 python3.10 python3.9; do
    command -v "$CAND" >/dev/null 2>&1 || continue
    RESOLVED="$(command -v "$CAND")"
    if "$RESOLVED" -c "import numpy.f2py" >/dev/null 2>&1; then
        PYTHON3="$RESOLVED"
        break
    fi
done

if [ -z "$PYTHON3" ]; then
    echo "ERROR: no python3 on PATH has a working numpy.f2py module." >&2
    echo "       fix with, e.g.: python3 -m pip install --user numpy" >&2
    exit 1
fi
NUMPY_VER="$("$PYTHON3" -c 'import numpy; print(numpy.__version__)')"
echo "    using $PYTHON3 (numpy $NUMPY_VER)"

WRAPPER="$MG5_DIR/f2py_wrapper.sh"
cat > "$WRAPPER" <<WRAPEOF
#!/usr/bin/env bash
# Auto-generated by setup.sh -- do not edit by hand, rerun setup.sh instead.
exec "$PYTHON3" -m numpy.f2py "\$@"
WRAPEOF
chmod +x "$WRAPPER"
echo "==> Wrote $WRAPPER"

echo "==> Checking compilers ..."
HAVE_FORTRAN=1
check_tool() {
    local tool="$1" hint="$2"
    if command -v "$tool" >/dev/null 2>&1; then
        echo "    OK      $tool -> $(command -v "$tool")"
    else
        echo "    MISSING $tool -- install with: $hint"
        if [ "$tool" = "gfortran" ]; then HAVE_FORTRAN=0; fi
    fi
}
case "$(uname -s)" in
    Darwin) check_tool gfortran "brew install gcc"; check_tool clang "xcode-select --install" ;;
    Linux)  check_tool gfortran "sudo apt-get install gfortran"; check_tool g++ "sudo apt-get install g++" ;;
    *)      check_tool gfortran "install a Fortran compiler"; check_tool g++ "install a C++ compiler" ;;
esac

if [ "$HAVE_FORTRAN" = "1" ]; then
    echo "==> Smoke-testing f2py wrapper ..."
    TMPD="$(mktemp -d)"
    trap 'rm -rf "$TMPD"' EXIT
    cat > "$TMPD/hello.f" <<'FORTRAN_EOF'
      subroutine hello(x, y)
      real*8 x, y
Cf2py intent(in) x
Cf2py intent(out) y
      y = x * 2.0d0
      end
FORTRAN_EOF
    if ( cd "$TMPD" && "$WRAPPER" -c -m hello hello.f ) >"$TMPD/f2py.log" 2>&1; then
        echo "    OK: wrapper compiles Fortran extensions."
    else
        echo "ERROR: f2py smoke test failed:" >&2
        cat "$TMPD/f2py.log" >&2
        exit 1
    fi
else
    echo "==> Skipping f2py smoke test (no gfortran) -- install it, then rerun setup.sh."
fi

patch_config() {
    local cfg="$1"
    [ -f "$cfg" ] || return 0
    if grep -qF "f2py_compiler_py3 = $WRAPPER" "$cfg" 2>/dev/null; then
        echo "[skip] $cfg already points at the wrapper"; return 0
    fi
    local tmp="$cfg.tmp.$$"
    grep -v -E '^#?[[:space:]]*f2py_compiler_py3[[:space:]]*=' "$cfg" > "$tmp"
    printf 'f2py_compiler_py3 = %s\n' "$WRAPPER" >> "$tmp"
    mv "$tmp" "$cfg"
    echo "==> Patched $cfg"
}

# Only the master template + user-level override -- deliberately NOT touching
# any already-generated PROC_*/ output, since those may belong to a run of
# create.sh that's still in flight.
patch_config "$MG5_DIR/input/mg5_configuration.txt"
patch_config "$HOME/.mg5/mg5_configuration.txt"

echo "==> f2py toolchain fix complete."
